course/urls.py
from django.urls import path, include
from .views import *

msg_urlpatterns = [
    path('', MsgList.as_view(), name='course_msglist'),
    path('broadcast/', MsgCreate.as_view(), name='course_msgbroadcast'),
]

assignment_urls = [
    path('', AssignmentList.as_view(), name='assignment_list'), 
    path('create/', AssignmentCreate.as_view(), name='assignment_create'),
    path('<int:aid>/', AssignmentView.as_view(), name='assignment_view'),
    path('<int:aid>/edit/', AssignmentEdit.as_view(), name='assignment_edit'),
    path('<int:aid>/submit/', WorkSubmit.as_view(), name='work_submit'),
    path('work/<int:wid>/', WorkUpdate.as_view(), name='work_update'),
    path('score/<int:wid>/', WorkScore.as_view(), name='work_score'),
]

remark_urls = [
    path('', RemarkUsers.as_view(), name='remark_users'),
    path('<int:uid>/', UserRemark.as_view(), name='user_remark'),
    path('assignment/<int:aid>/', AssignRemark.as_view(), name='remark_list'),
]

urlpatterns = [
    path('', CourseList.as_view(), name='course_list'), 
    path('create/', CourseCreate.as_view(), name='course_create'),
    path('<int:cid>/', CourseView.as_view(), name='course_view'), 
    path('<int:cid>/edit/', CourseEdit.as_view(), name='course_edit'),
    path('<int:cid>/enroll/', CourseEnroll.as_view(), name='course_enroll'), 
    path('<int:cid>/users/', CourseUsers.as_view(), name='course_users'),
    path('<int:cid>/seat/', CourseEnrollSeat.as_view(), name='course_seat'),
    path('<int:cid>/msg/', include(msg_urlpatterns)),
    path('<int:cid>/assign/', include(assignment_urls)),
    path('<int:cid>/remark/', include(remark_urls)),
    path('<int:cid>/score/', CourseScore.as_view(), name='course_score'),
]

eclassroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', 
        TemplateView.as_view(
            template_name='home.html', 
            extra_context={'title': '歡迎光臨'}
        ), 
        name='home'
    ),
    path('user/', include('user.urls')),
    path('course/', include('course.urls')),
] + static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT
)

user/urls.py
from django.urls import path, include
from .views import *

msg_urlpatterns = [
    path('', MsgList.as_view(), name='user_inbox'), 
    path('outbox/', MsgOutbox.as_view(), name='user_outbox'),
    path('<int:mid>/', MsgRead.as_view(), name='user_msgread'),
    path('<int:mid>/reply/', MsgReply.as_view(), name='user_msgreply'),
    path('send/<int:rid>/', MsgSend.as_view(), name='user_msgsend'), 
]

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', UserDashboard.as_view(), name='user_dashboard'),
    path('list/', UserList.as_view(), name='user_list'),
    path('register/', UserRegister.as_view(), name='user_register'),
    path('<int:pk>/', UserView.as_view(), name='user_view'),
    path('<int:pk>/edit/', UserEdit.as_view(), name='user_edit'),
    path('<int:pk>/password/', UserPasswordUpdate.as_view(), name='user_password'),
    path('<int:uid>/teacher/', UserTeacherToggle.as_view(), name='user_teacher_toggle'),
    path('msg/', include(msg_urlpatterns)),
    path('q/', QEdit.as_view(), name='q_edit'),
    path('q/create/', QCreate.as_view(), name='q_create'),
]

course/models.py
from django.db.models import *
from django.contrib.auth.models import User

# 課程
class Course(Model):
    name = CharField('課程名稱', max_length=32)
    enroll_password = CharField('選課密碼', max_length=32)
    teacher = ForeignKey(User, CASCADE)     # 開課教師

    def __str__(self):
        return "{}: {}({})".format(
            self.id,
            self.name, 
            self.teacher.first_name
        )

# 選課
class Enroll(Model):
    stu = ForeignKey(User, CASCADE)         # 選修學生
    course = ForeignKey(Course, CASCADE)    # 選修課程
    seat = IntegerField('座號', default=0)
    remark_score = IntegerField('心得成績', default=0)

    def __str__(self):
        return "{}: {}-{}-{}".format(
            self.id, 
            self.course.name, 
            self.seat, 
            self.stu.first_name
        )

# 作業
class Assignment(Model):
    title = CharField('作業名稱', max_length=255)
    desc = TextField('作業說明', null=True, default=None)
    course = ForeignKey(Course, CASCADE, related_name='assignments')
    created = DateTimeField('建立時間', auto_now_add=True)

    def __str__(self):
        return "{}:{}:{}".format(
            self.id, 
            self.course.name, 
            self.title
        )

import os

# 自訂上傳檔案的存檔檔名
def work_attach(instance, filename):
    _, ext = os.path.splitext(filename)
    return "assignment/{}/{}{}".format(
        instance.assignment.id, 
        instance.user.username, 
        ext
    )

# 作品
class Work(Model):
    assignment = ForeignKey(Assignment, CASCADE, related_name='works')
    user = ForeignKey(User, CASCADE, related_name='works')
    memo = TextField('心得', default='')
    attachment = FileField('附件', upload_to=work_attach, null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    score = IntegerField('成績', default=0)

    def save(self, *args, **kwargs):
        try:
            original = Work.objects.get(id=self.id)
            if original.attachment != self.attachment:
                original.attachment.delete(save=False)
        except:
            pass
        super().save(*args, **kwargs)

    def __str__(self):
        return "{}:({}){}-{}".format(
            self.id, 
            self.assignment.course.name, 
            self.assignment.title,
            self.user.first_name, 
        )

course/views.py
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.views.generic import *
from django.contrib.auth.mixins import *
from django.contrib import messages
from django import forms
from .models import *
from django.db.models import Subquery, OuterRef
from user.models import Message, PointHistory

class TeacherReqiuredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser and \
            not request.user.groups.filter(name='teacher').exists():
            return super().handle_no_permission()

        return super().dispatch(request, *args, **kwargs)

COURSE_PERM_GUEST = 0       # 僅非課程人員
COURSE_PERM_STUDENT = 1     # 是修課學生
COURSE_PERM_TEACHER = 2     # 是授課教師
COURSE_PERM_MEMBER = 3      # 是修課學生或授課教師

class CourseAccessMixin(AccessMixin):
    permission = None       # 預設不檢查權限
    extra_context = {}
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()

        self.course = get_object_or_404(Course, id=kwargs['cid'])

        user_perm = COURSE_PERM_GUEST
        if self.course.teacher == request.user:
            user_perm = COURSE_PERM_TEACHER
        elif self.course.enroll_set.filter(stu=request.user).exists():
            user_perm = COURSE_PERM_STUDENT
        
        if not request.user.is_superuser and self.permission is not None:
            is_accessible = False
            if self.permission == COURSE_PERM_GUEST and \
                user_perm == COURSE_PERM_GUEST:
                is_accessible = True
            elif (self.permission & user_perm) != 0:
                is_accessible = True

            if not is_accessible:
                return self.handle_no_permission()  

        self.extra_context.update({'course': self.course})
        return super().dispatch(request, *args, **kwargs)

class CourseList(ListView): # 課程列表
    extra_context = {'title': '課程列表'}
    model = Course
    ordering = ['-id']
    paginate_by = 20

class CourseCreate(TeacherReqiuredMixin, CreateView):    # 建立課程
    extra_context = {'title': '建立課程'}
    model = Course
    fields = ['name', 'enroll_password']
    template_name = 'form.html'
    success_url = reverse_lazy('course_list')

    def form_valid(self, form):
        form.instance.teacher = self.request.user
        return super().form_valid(form)

class CourseView(CourseAccessMixin, DetailView):    # 檢視課程
    extra_context = {'title': '檢視課程'}
    model = Course
    pk_url_kwarg = 'cid'

class CourseEdit(CourseAccessMixin, UpdateView):    # 修改課程
    permission = COURSE_PERM_TEACHER
    extra_context = {'title': '修改課程'}
    pk_url_kwarg = 'cid'
    model = Course
    fields = ['name', 'enroll_password']
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('course_view', args=[self.object.id])

class CourseEnroll(CourseAccessMixin, CreateView):  # 選修課程
    permission = COURSE_PERM_GUEST
    model = Enroll
    fields = ['seat']
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('course_view', args=[self.course.id])

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['title'] = '選修課程：' + self.course.name
        return ctx
    
    def get_form(self):
        form = super().get_form()
        form.fields['password'] = forms.CharField(label='選課密碼', max_length=32)
        return form
    
    def form_valid(self, form):
        if form.cleaned_data['password'] != self.course.enroll_password:
            form.add_error('password', '選課密碼錯誤')
            return super().form_invalid(form)
        form.instance.course = self.course
        form.instance.stu = self.request.user
        return super().form_valid(form)

class CourseUsers(CourseAccessMixin, ListView):  # 修課名單
    permission = COURSE_PERM_MEMBER
    extra_context = {'title': '修課名單'}
    template_name = 'course/user_list.html'

    def get_queryset(self):
        return self.course.enroll_set.select_related('stu')\
            .annotate(
                points = Sum('stu__point_list__point')
            ).order_by('seat')

class CourseEnrollSeat(CourseAccessMixin, UpdateView):  # 變更座號
    permission = COURSE_PERM_STUDENT
    extra_context = {'title': '變更座號'}
    fields = ['seat']
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('course_view', args=[self.course.id])

    def get_object(self):
        return get_object_or_404(
            Enroll,
            course=self.course,
            stu=self.request.user
        )

class MsgList(CourseAccessMixin, ListView):  # 公告列表
    permission = COURSE_PERM_MEMBER
    extra_context = {'title': '公告列表'}
    model = Message
    paginate_by = 20
    template_name = 'course/message_list.html'

    def get_queryset(self):
        return self.course.notices.annotate(
            read=Subquery(self.request.user.read_list.filter(
                message=OuterRef('id')).values('read'))
        ).order_by('-created')

class MsgCreate(CourseAccessMixin, CreateView):  # 教師新增課程公告
    permission = COURSE_PERM_TEACHER
    extra_context = {'title': '新增公告'}
    model = Message
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['success_url'] = self.request.META.get('HTTP_REFERER', '/')
        return ctx

    def form_valid(self, form):
        form.instance.course = self.course
        form.instance.sender = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, '公告已張貼！')
        return self.request.POST.get('success_url')

class AssignmentList(CourseAccessMixin, ListView):
    extra_context = {'title': '作業列表'}
    permission = COURSE_PERM_MEMBER
    paginate_by = 15

    def get_queryset(self):
        return self.course.assignments.annotate(
            submitted=Subquery(
                self.request.user.works.filter(
                    assignment=OuterRef('id')
                ).values('created')
            )
        ).order_by('-created')

class AssignmentCreate(CourseAccessMixin, CreateView):
    extra_context = {'title': '新增作業'}
    permission = COURSE_PERM_TEACHER
    model = Assignment
    fields = ['title', 'desc']

    def form_valid(self, form):
        form.instance.course = self.course
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('assignment_list', args=[self.course.id])

class AssignmentEdit(CourseAccessMixin, UpdateView):
    extra_context = {'title': '修改作業'}
    permission = COURSE_PERM_TEACHER
    model = Assignment
    fields = ['title', 'desc']
    pk_url_kwarg = 'aid'

    def get_success_url(self):
        return reverse('assignment_view', args=[self.course.id, self.object.id])

class AssignmentView(CourseAccessMixin, DetailView):
    extra_context = {'title': '檢視作業'}
    permission = COURSE_PERM_MEMBER
    model = Assignment
    pk_url_kwarg = 'aid'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_superuser or self.course.teacher == self.request.user:
            sq = self.object.works.filter(user=OuterRef('stu'))
            ctx['work_list'] = self.course.enroll_set.annotate(
                wid = Subquery(sq.values('id')), 
                submitted = Subquery(sq.values('created')),
                score = Subquery(sq.values('score')),
            ).order_by('seat').values('seat', 'stu__first_name', 'wid', 'submitted', 'score')
        else:
            mywork = self.object.works.filter(user=self.request.user).order_by('-id')
            if mywork:
                ctx['mywork'] = mywork[0]
        return ctx

class WorkSubmit(CourseAccessMixin, CreateView):
    extra_context = {'title': '繳交作業'}
    permission = COURSE_PERM_STUDENT
    model = Work
    fields = ['memo', 'attachment']
    template_name = 'form.html'

    def form_valid(self, form):
        form.instance.assignment = Assignment(id=self.kwargs['aid'])
        form.instance.user = self.request.user
        # 繳交作業累積 2 點積分
        PointHistory(
            user = form.instance.user,
            assignment = form.instance.assignment, 
            reason = '繳交作業', 
            point = 2
        ).save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse(
            'assignment_view', 
            args=[self.course.id, self.object.assignment.id]
        )

class WorkUpdate(UpdateView):
    extra_context = {'title': '修改作業'}
    model = Work
    fields = ['memo', 'attachment']
    template_name = 'form.html'
    pk_url_kwarg = 'wid'

    def get_object(self):
        work = super().get_object()
        if not work.user == self.request.user:
            raise PermissionDenied("欲修改的作業不是你做的，不允許改修")
        if work.score > 0:
            raise PermissionDenied("作業已完成評分，不允許修改")
        return work

    def get_success_url(self):
        return reverse(
            'assignment_view', 
            args=[self.course.id, self.object.assignment.id]
        )

class WorkScore(CourseAccessMixin, UpdateView):
    extra_context = {'title': '批改作業'}
    permission = COURSE_PERM_TEACHER
    model = Work
    fields = ['score']
    pk_url_kwarg = 'wid'

    def get_success_url(self):
        return reverse(
            'assignment_view', 
            args=[self.course.id, self.object.assignment.id]
        )
    
    def get_form(self):
        form = super().get_form()
        form.fields['score'] = forms.ChoiceField(
            label = '成績', 
            choices = [
                (100, "你好棒(100分)"), 
                (90, "90分"),
                (80, "80分"),
                (70, "70分"),
                (60, "60分"),
            ],
        )
        self.oldscore = self.object.score # 本次評分前原始成績
        return form
    

templates/course/assignment_detail.html
{% extends "course/course_detail.html" %}

{% load static %}

{% block course_detail_body %}
<div id="assignment-detail">
  <div class="d-flex border-bottom" style="justify-content: space-between;">
    <h2>{{ assignment.title }}</h2>
    {% if user.is_superuser or course.teacher == user %}
    <div>
      <a href="{% url 'assignment_edit' course.id assignment.id %}" class="btn btn-sm btn-primary">
        編輯作業
      </a>
      <a href="{% url 'remark_list' course.id assignment.id %}" class="btn btn-sm btn-info">
        查看心得
      </a>
    </div>
    {% endif %}
  </div>
  <div class="assignment-body">
    {{ assignment.desc|linebreaks }}
  </div>
</div>
<hr />
{% if user.is_superuser or course.teacher == user %}
<div id="work-list">
  {% for work in work_list %}
    <div class="work">
      {{ work.seat }} {{ work.stu__first_name }}
      {% if not work.wid %}
        <span class="badge badge-danger">未繳交</span>
      {% else %}
        <a href="{% url 'work_score' course.id work.wid %}">
          <span class="badge badge-success">
            <i class="fas fa-upload"></i> {{ work.submitted }}
          </span>
          <i class="fas fa-pen-square"></i> 批改
        </a>
        {% if work.score > 0 %}
          <span class="score px-2">{{ work.score }}</span>
        {% endif %}
      {% endif %}
    </div>
  {% endfor %}
</div>
{% else %}
<div id="work-detail">
  {% if mywork %}
    <div class="card">
      {% if mywork.memo %}
      <div class="card-body">
        {% if mywork.score > 0 %}
          <div class="text-right">
            <span class="score px-2">{{ mywork.score }}</span>
          </div>
        {% endif %}
        {{ mywork.memo|linebreaks }}
      </div>
      {% endif %}
      <div class="card-footer d-flex">
        {% if mywork.attachment %}
        <div>
          <i class="fas fa-paperclip"></i>
          <a href="{{ mywork.attachment.url }}">
            附件下載
          </a>
        </div>
        {% endif %}
        <div class="ml-auto">
          <a href="{% url 'work_update' course.id mywork.id %}">
            <i class="fas fa-edit"></i>
          </a>
          <span class="badge badge-light">{{ mywork.created }}</span>
        </div>
      </div>
    </div>
  {% else %}
    <a href="{% url 'work_submit' course.id assignment.id %}" class="btn btn-sm btn-primary">
      <i class="fas fa-upload"></i> 繳交作業
    </a>
  {% endif %}
</div>
{% endif %}
{% endblock %}

templates/course/assignment_form.html
{% extends "course/course_detail.html" %}

{% block course_detail_body %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="card">
    <div class="card-body">
      <table class="table table">
        {{ form.as_table }}
      </table>
    </div>
    <div class="card-footer">
      <input type="submit" value="送出" class="btn btn-primary">
    </div>
  </div>
</form>
{% endblock %}

{% block custom_scripts %}
<script>
add_css_class('form table input, form table textarea', 'form-control');
add_css_class('.errorlist', 'alert', 'alert-danger');
add_css_class('.helptext ul', 'alert', 'alert-light');
</script>
{% endblock %}

templates/course/assignment_list.html
{% extends "course/course_detail.html" %}

{% load user_tags %}

{% block course_detail_body %}
{% if user|is_teacher %}
<div class="mb-2">
  <a href="{% url 'assignment_create' course.id %}" class="btn btn-sm btn-primary">
    新增作業
  </a>
</div>  
{% endif %}
<div id="course_list" class="list-group">
  {% for assignment in assignment_list %}
    <div class="list-group-item d-md-flex">
      <a href="{% url 'assignment_view' course.id assignment.id %}">
        {{ assignment.title }}
      </a>
      <div class="ml-auto">
        <small>
        {% if assignment.submitted %}
          <i class="fas fa-upload"></i>
          {{ assignment.submitted|date:"Y-m-d H:i" }}
        {% else %}
          {% if not user == course.teacher and not user.is_superuser %}
          <span class="badge badge-danger">未繳交</span>
          {% endif %}
        {% endif %}
        <i class="fas fa-clock"></i>
        {{ assignment.created|date:"Y-m-d H:i" }}
        </small>
      </div>
    </div>
  {% endfor %}
</div>
{% include "pagination.html" %}
{% endblock %}

templates/course/course_detail.html
{% extends "base.html" %}

{% load user_tags %}

{% block content %}
<div id="course_view" class="card">
  {% with b1="btn btn-sm btn-primary" b2="btn btn-sm btn-secondary" %}
  <div class="card-header d-flex">
    <div>
      <a href="{% url 'course_view' course.id %}">{{ course.name }}</a>
      <small>{{ course.teacher.first_name }} 老師</small>
    </div>
    {% if user.is_superuser or course.teacher == user %}
    <div class="ml-auto">
      <span class="badge badge-light">
        選課密碼： {{ course.enroll_password }}
      </span>
      <a href="{% url 'course_edit' course.id %}" class="{{ b1 }}">
        <i class="fas fa-edit"></i> 編輯
      </a>
    </div >
    {% endif %}
  </div>
  <div class="card-body">
    {% block course_detail_body %}
    <div id="student_op" class="btn-group">
      {% if not course|has_member:user and not user.is_superuser %}
      <a href="{% url 'course_enroll' course.id %}" class="{{ b1 }}">
        <i class="fas fa-id-badge"></i> 選修
      </a>
      {% else %}
      <a href="{% url 'course_users' course.id %}" class="{{ b1 }}">
        <i class="fas fa-users"></i> 修課名單
      </a>
      <a href="{% url 'course_msglist' course.id %}" class="{{ b1 }}">
        <i class="fas fa-list"></i> 公告列表
      </a>
      <a href="{% url 'assignment_list' course.id %}" class="{{ b1 }}">
        <i class="fas fa-list"></i> 作業
      </a>
        {% if course|has_student:user %}
        <a href="{% url 'user_msgsend' course.teacher_id %}" class="{{ b1 }}">
          <i class="fas fa-paper-plane"></i> 提問
        </a>
        <a href="{% url 'course_seat' course.id %}" class="{{ b1 }}">
          <i class="fas fa-chair"></i> 更改座號
        </a>
        {% endif %}
      {% endif %}
    </div>
      {% if course.teacher == user %}
      <div id="teacher_op" class="btn-group">
        <a href="{% url 'course_msgbroadcast' course.id %}" class="{{ b2 }}">
          <i class="fas fa-bullhorn"></i> 發布公告
        </a>
        <a href="{% url 'remark_users' course.id %}" class="{{ b2 }}">
          <i class="fas fa-lightbulb"></i> 學生心得
        </a>
        <a href=" {% url 'course_score' course.id %}" class="{{ b2 }}">
          <i class="fas fa-th"></i> 成績總表
        </a>
      </div>
      {% endif %}
    {% endblock %}
  </div>
  {% endwith %}
</div>
{% endblock %}

templates/course/course_list.html
{% extends "base.html" %}

{% load user_tags %}

{% block content %}
{% if user|is_teacher %}
<div class="mb-2">
  <a href="{% url 'course_create' %}" class="btn btn-sm btn-primary">建立課程</a>
</div>  
{% endif %}
<div id="course_list" class="list-group">
  {% for course in course_list %}
  <div class="list-group-item d-flex">
    {% if user.is_authenticated %}
      <a href="{% url 'course_view' course.id %}">{{ course.name }}</a>
    {% else %}
      {{ course.name }}
    {% endif %}
    <small class="ml-auto">{{ course.teacher.first_name }} 老師</small>
  </div>
  {% endfor %}
</div>
{% include "pagination.html" %}
{% endblock %}

templates/course/course_score.html
{% extends "course/course_detail.html" %}

{% block course_detail_body %}
<table class="table table-sm">
  <thead>
    <tr>
      <th>學生</th>
      {% for a in assignment_list %}
      <th>
        <span class="badge badge-dark">{{ forloop.counter }}</span>
        {{ a.title }}
      </th>
      {% endfor %}
      <th>心得</th>
      <th>平均</th>
    </tr>
  </thead>
  <tbody>
    {% for stu in student_list %}
    <tr>
      <td>
        <span class="badge badge-primary">{{ stu.seat }}</span>
        {{ stu.stu.first_name }}
      </td>
      {% for s in stu.scores %}
      <td>{{ s }}</td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/course/message_list.html
{% extends "base.html" %}

{% block content %}
<ul class="list-group">
  {% for msg in message_list %}
  <li class="list-group-item d-md-flex">
    <a href="{% url 'user_msgread' msg.id %}">
      <span class="badge badge-danger">課程公告</span>
      {{ msg.title }}
      {% if not msg.read %}
        <span class="badge badge-warning">New!</span>
      {% endif %}
    </a>
    <div class="ml-auto">
      <small class="text-muted">
        <i class="fas fa-clock"></i> {{ msg.created }}
      </small>
    </div>
  </li>
  {% endfor %}
</ul>
{% include "pagination.html" %}
{% endblock %}

templates/course/remark_list.html
{% extends "course/course_detail.html" %}

{% block course_detail_body %}
<h2>{{ atitle }}</h2>
<div id="work-list">
  {% for work in object_list  %}
  <div class="work d-flex">
    <div class="user-info mr-2">
      <span class="badge badge-primary">
        {{ work.seat }}
        {{ work.stu__first_name }}
      </span>
    </div>
    <div class="remark">
      {% if work.remark %}
        {{ work.remark|linebreaksbr }}
      {% else %}
        <span class="badge badge-danger">
          尚未繳交
        </span>        
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/course/remark_score.html
{% extends "base.html" %}

{% block content %}
<div class="card">
  <div class="card-header">
    <h2>
      <span class="badge badge-primary">
        {{ stu.seat }}
      </span>
      {{ stu.stu__first_name }}
    </h2>
  </div>
  <div class="card-body" id="work-list">
    {% for a in assignment_list %}
    <div class="work">
      <div class="assignment">
        <span class="badge badge-primary">
          {{ forloop.counter }}
        </span>
        <a href="{% url 'assignment_view' a.course_id a.id %}">
          {{ a.title }}
        </a>
      </div>
      <div class="remark">
        {% if a.remark %}
          {{ a.remark|linebreaksbr }}
        {% else %}
          <span class="badge badge-danger">未繳交</span>
        {% endif %}
      </div>
    </div>    
    {% endfor %}
  </div>
  <div class="card-footer">
    <form action="" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="評分" class="btn btn-sm btn-primary">
    </form>
  </div>
</div>
{% endblock %}

templates/course/remark_users.html
{% extends "course/course_detail.html" %}

{% block course_detail_body %}
<div id="work-list">
  {% for stu in enroll_list %}
  <div class="work">
    <span class="badge badge-light">{{ stu.seat }}</span>
    {% with cid=course.id sid=stu.stu_id %}
      {{ stu.stu.first_name }}
      <a href="{% url 'user_remark' cid sid %}" class="btn btn-sm btn-primary">
        <i class="fas fa-search"></i> 查看心得
      </a>
    {% endwith %}
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/course/user_list.html
{% extends "course/course_detail.html" %}

{% block course_detail_body %}
<div id="course_users">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>學校</th>
        <th>帳號</th>
        <th>座號</th>
        <th>姓名</th>
        <th>積分</th>
        <th>最近登入時間</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for enroll in enroll_list %}
      <tr>
        <td>{{ enroll.stu.last_name }}</td>
        <td>{{ enroll.stu.username }}</td>
        <td>{{ enroll.seat }}</td>
        <td>{{ enroll.stu.first_name }}</td>
        <td>{{ enroll.points|default:0 }}</td>
        <td>{{ enroll.stu.last_login|date:"Y-m-d H:i" }}</td>
        <td>
          {% if enroll.stu_id != user.id %}
          <a href="{% url 'user_msgsend' enroll.stu_id %}" class="btn btn-sm btn-secondary">
            <i class="fas fa-paper-plane"></i> 傳訊
          </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/course/work_form.html
{% extends "course/course_detail.html" %}

{% load static %}

{% block course_detail_body %}
<div id="work-detail" class="card">
  <div class="card-header">
    {{ object.user.first_name }}
  </div>
  <div class="card-body">
    {{ object.memo|linebreaks }}
    {% if object.attachment %}
    <a href="{% get_media_prefix %}{{ object.attachment }}">
      <i class="fas fa-paperclip"></i> 副件下載
    </a>
    {% endif %}
  </div>
  <div class="card-footer">
    <form action="" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="送出" class="btn btn-sm btn-primary">
    </form>
  </div>
</div>
{% endblock %}